title: Art Gallery
author: CoffeeGoddess
email: coffeegoddess@rdil.rocks
description: > # this means to ignore newlines until "baseurl:"
  I'm a professional artist who loves coffee, of course. 
  Feel free to check it out on the link below...

# social links
github_username: CoffeeGoddess

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima 
